### ISSUE TITLE
BUG - Child pages are not added if current page is ignored

### ISSUE THREAD

**Issue by flowertwig-org** [7h3Rabbit/StaticWebEpiserverPlugin#39]
Child pages are not added if current page is ignored.
This should be changed, child pages may be interesting even if current page is not

https://github.com/7h3Rabbit/StaticWebEpiserverPlugin/blob/eb80f831966479db4bbf9229b1b30428bd56cff1/ScheduledJobs/StaticWebScheduledJob.cs#L259

**Comment by 7h3Rabbit** [comment]
Solved
