### ISSUE TITLE
Add support for generating static webb to azure

### ISSUE THREAD

**Issue by maer0216-star** [7h3Rabbit/StaticWebEpiserverPlugin#49]
It would be nice if the plugin supported azure as target platform for a static webb. The static webb in azure should be generated from scratch from the scheduled jobb as well as updated whenever a change/add/delete occur on a block or page. I.e same functionality as for a static webb on disk. In azure the files should be stored in a blob storage container.

**Comment by 7h3Rabbit** [comment]
We have now added to new events.
### AfterIOWrite
Is called AFTER a file has been written to disk.
This is usefull to run code after folder has been updated.
For example an azcopy call.

### AfterIODelete
Is called AFTER a file has been written to disk.
This is usefull to run code after folder has been updated.
For example an azcopy call.


### Example use:
![image](https://user-images.githubusercontent.com/62792609/143612130-ff51a44d-ec6c-4200-9461-f6f2289fd3f1.png)

**Comment by 7h3Rabbit** [comment]
You can read more about AzCopy here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-blobs-synchronize

**Comment by 7h3Rabbit** [comment]
I used "Get Shared Access Signature" option on my blob container when using Microsoft Azure Storage Explorer.
This way I got the required <login params> to use in the above example and made it easy to define how long access should be vaild and also what it should be valid for.
