### ISSUE TITLE
Bug: Source tags only allow one image reference, not image candidate(s)

### ISSUE THREAD

**Issue by themaf** [7h3Rabbit/StaticWebEpiserverPlugin#51]
We are currently building a new Episerver website and have been using your plugin to generate a static web, and it has been working very well for us. But now, I have run into an issue with converting images to webp.

When an image on our website is rendered on the page it generates a picture-tag. For example: 

```
<picture>
    <source sizes="(max-width: 767px) 720px, (max-width: 991px) 1152px, 1350px" srcset="/globalassets/folder/image.jpg?format=webp&amp;width=720&amp;quality=90 720w, /globalassets/folder/image.jpg?format=webp&amp;width=1152&amp;quality=90 1152w, /globalassets/folder/image.jpg?format=webp&amp;width=1350&amp;quality=90 1350w" type="image/webp">
    <source sizes="(max-width: 767px) 720px, (max-width: 991px) 1152px, 1350px" srcset="/globalassets/folder/image.jpg?width=720&amp;quality=90 720w, /globalassets/folder/image.jpg?width=1152&amp;quality=90 1152w, /globalassets/folder/image.jpg?width=1350&amp;quality=90 1350w">
    <img alt="" src="/globalassets/folder/image.jpg?width=1350&amp;quality=90" loading="lazy">
</picture>
```

When we generate our static web the code above turns into:

```
<picture>
    <source sizes="(max-width: 767px) 720px, (max-width: 991px) 1152px, 1350px" srcset="/globalassets/folder/image.jpg?format=webp&amp;width=720&amp;quality=90 720w, /globalassets/folder/image.jpg?format=webp&amp;width=1152&amp;quality=90 1152w, /globalassets/folder/image.jpg?format=webp&amp;width=1350&amp;quality=90 1350w" type="image/webp">
    <source sizes="(max-width: 767px) 720px, (max-width: 991px) 1152px, 1350px" srcset="/globalassets/folder/image.jpg?width=720&amp;quality=90 720w, /globalassets/folder/image.jpg?width=1152&amp;quality=90 1152w, /cache/v1/KY0.1OwtD0RyHiyM0ctHGHr6mDeXtXyDNRk-MFaaefg_.jpg 1350w">
    <img alt="" src="/cache/v1/KY0.1OwtD0RyHiyM0ctHGHr6mDeXtXyDNRk-MFaaefg_.jpg" loading="lazy">
</picture>
```

As you can see, only the src in the img-tag and the last url in the srcset in the second source-tag gets changed so that it points to an image in the resource folder. All the other url:s still point to the globalassets folder in our episerver-site.

Am I doing something wrong or are picture tags not supported? If picture tags are not supported, would it be possible to add support for them?

**Comment by 7h3Rabbit** [comment]
@themaf This is not related to webp.
Turns out that we currently only allow one image reference for every srcset today.
We don't support image candidate as you use and not multiple of them.
I will look in to this and get back.

**Comment by 7h3Rabbit** [comment]
@themaf a fix can be found in branch `issue-51` ( https://github.com/7h3Rabbit/StaticWebEpiserverPlugin/tree/issue-51 ).
It has not been tested yet or even compiled but it should work and if you are in a hurry you can test it and let me know if it solves your issue.
If you can't test it I will probably have time to do so in the end of the weekend or later next week.

**Comment by 7h3Rabbit** [comment]
Solved and closed.
Thanks for letting me know :)

**Comment by themaf** [comment]
@7h3Rabbit Thank you for your quick response!
