### ISSUE TITLE
Draft pages is generated by the static webb job 

### ISSUE THREAD

**Issue by maer0216-star** [7h3Rabbit/StaticWebEpiserverPlugin#66]
When the Generate StaticWeb job is triggered, pages that has not been published are genereted to the static webb. The content of the generated index.html file is the 404 page and not the actual content of the page.

The expected behaviour would be not to generate pages for draft/unpublished pages when the  Generate StaticWeb job is triggered.  In case a fix is implemented it would be nice if draft/unpublished pages that has previously been created are deleted.

**Comment by 7h3Rabbit** [comment]
It turns out that if your website has not configured your 404 page to actually return 404 status code this can happen.
This is why this has not been found before as the Optimizly (previously EpiServer) Alloy project is returning status code 404 for pages not found.

**Comment by 7h3Rabbit** [comment]
I have done following changes:
- We now verify that page is indeed published when running scheduled job (so 404 pages that is returning 200 is not generated).
- If you use the `RemoveObsoletePages `functionality it will now also remove pages that is not published (solving your issue for pages that has already been generated)

**Comment by 7h3Rabbit** [comment]
Thanks for finding this issue and reporting it :)
I am now marking it as solved.
