### ISSUE TITLE
Bug - Resource finding can't handle multiple resources on same line

### ISSUE THREAD

**Issue by maer0216-star** [7h3Rabbit/StaticWebEpiserverPlugin#72]
Hi,

the plugin fails to generate a image if the image is located in a <p> tag that also contains a <a> tag.

This code does not trigger a image generation:
`<p><img src="/EPiServer/CMS/Content/siteassets/instagram-icon.png,,232?epieditmode=False" alt="instagram-icon.png" width="20" height="20" />sdasasdasddsa<a title="jkjkhkhjkh" href="http://www.vk.se">adadadas</a></p>`

This code generates a image
`<p><img src="/EPiServer/CMS/Content/siteassets/instagram-icon.png,,232?epieditmode=False" alt="instagram-icon.png" width="20" height="20" />sdasasdasddsa</p><p><a title="jkjkhkhjkh" href="http://www.vk.se">adadadas</a></p>`

The above code is generated by tinymce

Configuration
` new AllowedResourceTypeConfigurationElement() { FileExtension = ".png", MimeType = "image/png", UseHash = false, UseResourceUrl = true, UseResourceFolder = false  },`

Any ideas?

regards
Magnus

**Comment by maer0216-star** [comment]
Thanks, it works!

**Comment by 7h3Rabbit** [comment]
@maer0216-star Thanks for the bug report :)
