### ISSUE TITLE
Abort update of page if not all resources could be loaded

### ISSUE THREAD

**Issue by ErikJJonsson** [7h3Rabbit/StaticWebEpiserverPlugin#77]
We have a scenario where some resources are loaded from external sources via API:s.
If a page is re-published when a sources is unavailable then a complete "page" is replaced with an newer version which lacks some resources. We would rather keep the complete "page".

Would it be possible to add support to abort update of a page if not all it´s resources could be loaded?
Maybe by making it an option.

I don´t know if it´s needed to differentiate between internal and external resources if that makes anything easier.

**Comment by 7h3Rabbit** [comment]
Can you supply any examples?

**Comment by ErikJJonsson** [comment]
We don't need this requested change anymore so I will this issue.
